#!/bin/bash
#this is my final to spin up a network

#1 This script spins up an rsyslog server
gcloud compute instances create rsyslog2 \
--image-family centos-7 \
--image-project centos-cloud \
--zone us-east1-b \
#--tags "http-server","https-server" \ - this line is not required 
--machine-type f1-micro \
--scopes cloud-platform \
--metadata-from-file startup-script=NTI-310/hello-nti-310/config/

#2 This script spins up a postgres server
gcloud compute instances create postgres2 \
--image-family centos-7 \
--image-project centos-cloud \
--zone us-east1-b \
--tags "http-server","https-server" \
--machine-type f1-micro \
--scopes cloud-platform \
--metadata-from-file startup-script=NTI-310/hello-nti-310/config/postgrestest1
#needs to be the name of the client rsyslog server
echo "postgrestest1@@rsyslog:514" >> /etc/rsyslog.conf
systemctl restart rsyslog
systemctl enable rsyslog

#3 This script spins up an ldap server
gcloud compute instances create ldap2 \
--image-family centos-7 \
--image-project centos-cloud \
--zone us-east1-b \
--tags "http-server","https-server" \
--machine-type f1-micro \
--scopes cloud-platform \
--metadata-from-file startup-script=NTI-310/hello-nti-310/config/continue_ldap_install
#needs to be the name of the client rsyslog server
echo "continue_ldap_install@@rsyslog:514" >> /etc/rsyslog.conf
systemctl restart rsyslog
systemctl enable rsyslog

#4 This script spins up a nfs server
gcloud compute instances create nfs2 \
--image-family centos-7 \
--image-project centos-cloud \
--zone us-east1-b \
#--tags "http-server","https-server" \ - this line is not required
--machine-type f1-micro \
--scopes cloud-platform \
--metadata-from-file startup-script=NTI-310/hello-nti-310/config/nfs-a install
#needs to be the name of the client rsyslog server
echo "nfs-a install@@rsyslog:514" >> /etc/rsyslog.conf
systemctl restart rsyslog
systemctl enable rsyslog

#5 This script spins up a django  server
gcloud compute instances create django2 \
--image-family centos-7 \
--image-project centos-cloud \
--zone us-east1-b \
--tags "http-server","https-server" \
--machine-type f1-micro \
--scopes cloud-platform \
--metadata-from-file startup-script=NTI-310/hello-nti-310/config/djangopostgres
#needs to be the name of the client rsyslog server
echo "djangopostgres@@rsyslog:514" >> /etc/rsyslog.conf
systemctl restart rsyslog
systemctl enable rsyslog

#6 This script spins up client1 
gcloud compute instances create client1 \
--image-family centos-7 \
--image-project centos-cloud \
--zone us-east1-b \
#--tags "http-server","https-server" \ - this line not required
--machine-type f1-micro \
--scopes cloud-platform \
--metadata-from-file startup-script=NTI-310/hello-nti-310/config/continue_ldap_install

#7 This script spins up client2 
gcloud compute instances create client2 \
--image-family centos-7 \
--image-project centos-cloud \
--zone us-east1-b \
#--tags "http-server","https-server" \ - this line not required
--machine-type f1-micro \
--scopes cloud-platform \
--metadata-from-file startup-script=NTI-310/hello-nti-310/config/continue_ldap_install
