#!/bin/bash
#this is the script for the NTI midterm

#1 This script spins up an rsyslog server
gcloud compute instances create rsyslog2 \
--image-family centos-7 \
--image-project centos-cloud \
--zone us-east1-b \
--machine-type f1-micro \
--scopes cloud-platform \
--metadata-from-file startup-script=NTI-310/hello-nti-310/config/Rsyslog
#sleep 30s

#2 This script spins up a nagios server
gcloud compute instances create nagios2 \
--image-family centos-7 \
--image-project centos-cloud \
--zone us-east1-b \
--machine-type f1-micro \
--scopes cloud-platform \
--metadata-from-file startup-script=NTI-310/hello-nti-310/config/Rsyslog

#3 This script spins up a cacti server
gcloud compute instances create cacti2 \
--image-family centos-7 \
--image-project centos-cloud \
--zone us-east1-b \
--machine-type f1-micro \
--scopes cloud-platform \
--metadata-from-file startup-script=NTI-310/hello-nti-310/config/Rsyslog

#4 This script spins up a postgres server
gcloud compute instances create postgres2 \
--image-family centos-7 \
--image-project centos-cloud \
--zone us-east1-b \
--tags "http-server","https-server" \
--machine-type f1-micro \
--scopes cloud-platform \
--metadata-from-file startup-script=NTI-310/hello-nti-310/config/postgrestest1
#sleep 30s
#This script spins up an rsyslog client
vim NTI-310/hello-nti-310/config/postgrestest1
#sleep 15s

#5 This script spins up an ldap server
gcloud compute instances create ldap2 \
--image-family centos-7 \
--image-project centos-cloud \
--zone us-east1-b \
--tags "http-server","https-server" \
--machine-type f1-micro \
--scopes cloud-platform \
--metadata-from-file startup-script=NTI-310/hello-nti-310/config/continue_ldap_install
#sleep 30s
#This script spins up an rsyslog client
vim NTI-310/hello-nti-310/config/continue_ldap_install

#6 This script spins up a nfs server
gcloud compute instances create nfs2 \
--image-family centos-7 \
--image-project centos-cloud \
--zone us-east1-b \
--machine-type f1-micro \
--scopes cloud-platform \
--metadata-from-file startup-script=NTI-310/hello-nti-310/config/nfs_install
#sleep 30s
#This script spins up an rsyslog client

#7 This script spins up a django  server
gcloud compute instances create django2 \
--image-family centos-7 \
--image-project centos-cloud \
--zone us-east1-b \
--tags "http-server","https-server" \
--machine-type f1-micro \
--scopes cloud-platform \
--metadata-from-file startup-script=NTI-310/hello-nti-310/config/djangopostgres
#sleep 30s
#This script spins up an rsyslog client

#8 This script spins up nfsclient2 
gcloud compute instances create nfsclient2 \
--image-family ubuntu-1804-lts \
--image-project ubuntu-os-cloud \
--zone us-east1-b \
--machine-type f1-micro \
--scopes cloud-platform \
--metadata-from-file startup-script=NTI-310/hello-nti-310/config/client-a
#sleep 10s

#9 This script spins up ldapclient2 
gcloud compute instances create ldapclient2 \
--image-family ubuntu-1804-lts \
--image-project ubuntu-os-cloud \
--zone us-east1-b \
--machine-type f1-micro \
--scopes cloud-platform \
--metadata-from-file startup-script=NTI-310/hello-nti-310/config/ldapclient.sh
