#!/bin/bash
#this is the script for the NTI midterm
#Adding the build server on the front end
gcloud compute instances create rpmbuild2 \
--image-family centos-7 \
--image-project centos-cloud \
--zone us-east1-c \
--machine-type f1-micro \
--scopes cloud-platform \
--metadata-from-file startup-script=NTI-310/hello-nti-310/config/buildrpm

#1 This script spins up an rsyslog server
gcloud compute instances create rsyslog2 \
--image-family centos-7 \
--image-project centos-cloud \
--zone us-east1-c \
--machine-type f1-micro \
--scopes cloud-platform \
--metadata-from-file startup-script=NTI-310/hello-nti-310/config/Rsyslog
#sleep 30s

#2 This script spins up a nagios server
gcloud compute instances create nagios2 \
--image-family centos-7 \
--image-project centos-cloud \
--zone us-east1-c \
--tags "http-server","https-server" \
--machine-type f1-micro \
--scopes cloud-platform \
--metadata-from-file startup-script=NTI-310/hello-nti-310/config/nagios4419

#3 This script spins up a cacti server
gcloud compute instances create cacti2 \
--image-family centos-7 \
--image-project centos-cloud \
--zone us-east1-c \
--tags "http-server","https-server" \
--machine-type f1-micro \
--scopes cloud-platform \
--metadata-from-file startup-script=NTI-310/hello-nti-310/config/cacti_install

#4 This script spins up a postgres server
gcloud compute instances create postgres2 \
--image-family centos-7 \
--image-project centos-cloud \
--zone us-east1-c \
--tags "http-server","https-server" \
--machine-type f1-micro \
--scopes cloud-platform \
--metadata-from-file startup-script=NTI-310/hello-nti-310/config/postgrestest1
#sleep 30s
#This script spins up an rsyslog client
#vim NTI-310/hello-nti-310/config/postgrestest1
#sleep 15s

#5 This script spins up an ldap server
gcloud compute instances create ldap2 \
--image-family centos-7 \
--image-project centos-cloud \
--zone us-east1-c \
--tags "http-server","https-server" \
--machine-type f1-micro \
--scopes cloud-platform \
--metadata-from-file startup-script=NTI-310/hello-nti-310/config/continue_ldap_install
#sleep 30s
#This script spins up an rsyslog client
#vim NTI-310/hello-nti-310/config/continue_ldap_install

#6 This script spins up a nfs server
gcloud compute instances create nfs2 \
--image-family centos-7 \
--image-project centos-cloud \
--zone us-east1-c \
--machine-type f1-micro \
--scopes cloud-platform \
--metadata-from-file startup-script=NTI-310/hello-nti-310/config/nfs_install
#sleep 30s
#This script spins up an rsyslog client

#7 This script spins up a django  server
gcloud compute instances create django2 \
--image-family centos-7 \
--image-project centos-cloud \
--zone us-east1-c \
--tags "http-server","https-server" \
--machine-type f1-micro \
--scopes cloud-platform \
--metadata-from-file startup-script=NTI-310/hello-nti-310/config/djangopostgres
#sleep 30s
#This script spins up an rsyslog client

#8 This script spins up nfsclient2 
gcloud compute instances create nfsclient2 \
--image-family ubuntu-1804-lts \
--image-project ubuntu-os-cloud \
--zone us-east1-c \
--machine-type f1-micro \
--scopes cloud-platform \
--metadata-from-file startup-script=NTI-310/hello-nti-310/config/client-a
#sleep 10s

#9 This script spins up ldapclient2 
gcloud compute instances create ldapclient2 \
--image-family ubuntu-1804-lts \
--image-project ubuntu-os-cloud \
--zone us-east1-c \
--machine-type f1-micro \
--scopes cloud-platform \
--metadata-from-file startup-script=NTI-310/hello-nti-310/config/ldapclient.sh

#for servername in $(gcloud compute instances list | awk '{print $1}' | sed "1 d" | grep -v nagios4419 );  do gcloud compute ssh --zone us-east1-c koda@$servername --command='sudo yum -y install wget && sudo wget https://raw.githubusercontent.com/dakoda17/NTI-310/master/hello-nti-310/config/nagiosclient421 && sudo bash nagiosclient421'; done

#!/bin/bash
#-v removes anything that matches nagios 
for servername in $(gcloud compute instances list | awk '{print $1}' | sed "1 d" | grep -v nagios2 );  do 
    echo $servername;
    serverip=$( gcloud compute instances list | grep $servername | awk '{print $4}');
    echo $serverip ;
    bash scp_to_nagios.sh $servername $serverip
done
gcloud compute ssh --zone us-east1-c koda@nagios2 --command='sudo systemctl restart nagios'

for servername in $(gcloud compute instances list | awk '{print $1}' | sed "1 d" | grep -v nagios2 );  do 
    gcloud compute ssh --zone us-east1-c koda@$servername --command='sudo yum -y install wget && sudo wget https://raw.githubusercontent.com/dakoda17/NTI-310/master/hello-nti-310/config/nagiosclient421.sh && sudo bash nagiosclient421.sh'
done
