#!/bin/bash
#This script spins up an ubuntu client-a

#this line installs the nfs-client for the ubuntu 18.04LS
apt-get install -y nfs-client

#a testing location
mkdir /mnt/test

#this line echos the files and places them in the /etc/fstab
echo "nfs2:/var/nfsshare/testing     /mnt/test     nfs     defaults 0 0" >> /etc/fstab

#this line proves its in the file
#vim /etc/fstab
#for servername in $(gcloud compute instances list | awk '{print $1}' | sed "1 d" | grep -v nagios4419 );  do gcloud compute ssh --zone us-east1-b koda@$servername --command='sudo yum -y install wget && sudo wget https://raw.githubusercontent.com/dakoda17/NTI-310/master/hello-nti-310/config/nagiosclient421 && sudo bash nagiosclient421'; done

#this line mounts it
mount -a

#============intstall cacti client=================
# install snmp and tools
yum -y install net-snmp net-snmp-utils

# create a new snmpd.conf
mv /etc/snmp/snmpd.conf /etc/snmp/snmpd.conf.orig
touch /etc/snmp/snmpd.conf

# edit snmpd.conf file /etc/snmp/snmpd.conf - also make sure the network is pointing to your internal network
echo '# create myuser in mygroup authenticating with 'public' community string and source network 10.150.0.0/24
com2sec myUser 10.150.0.0/24 public
# myUser is added into the group 'myGroup' and the permission of the group is defined
group    myGroup    v1        myUser
group    myGroup    v2c        myUser
view all included .1
access myGroup    ""    any    noauth     exact    all    all    none' >> /etc/snmp/snmpd.conf

# Enable snmp, Start snmp
systemctl enable snmpd
systemctl start snmpd

#================install rsyslog client===============
#This script spins up an rsyslog client

#client automation
yum -y update && yum -y install rsyslog
systemctl start rsyslog
systemctl enable rsyslog
cp /etc/rsyslog.conf /etc/rsyslog.bak

#needs to be the name of the client rsyslog server
echo "*.*  @@rsyslog:514" >> /etc/rsyslog.conf
systemctl restart rsyslog
systemctl enable rsyslog

#use the following to check to see that the client is logging onto the rsyslog server
#tail -F var/log/messages 
#echo "some text" | logger - this is a neat way to monitor what your rsyslog server is doing

