#!/bin/bash
#This script spins up an ubuntu client-a

#this line installs the nfs-client for the ubuntu 18.04LS
apt-get install -y nfs-client

#a testing location
mkdir /mnt/test

#this line echos the files and places them in the /etc/fstab
echo "nfs2:/var/nfsshare/testing     /mnt/test     nfs     defaults 0 0" >> /etc/fstab

#this line proves its in the file
#vim /etc/fstab
#for servername in $(gcloud compute instances list | awk '{print $1}' | sed "1 d" | grep -v nagios4419 );  do gcloud compute ssh --zone us-east1-b koda@$servername --command='sudo yum -y install wget && sudo wget https://raw.githubusercontent.com/dakoda17/NTI-310/master/hello-nti-310/config/nagiosclient421 && sudo bash nagiosclient421'; done

#this line mounts it
mount -a
