#!/bin/bash
#TEACHER COMMENTS/EDITS
#https://www.server-world.info/en/note?os=CentOS_7&p=openldap
#This is a basis for students to create a fully functioning build, compile, and deploy script.

#this line installs the server and client version of ldap software
yum -y install openldap-servers openldap-clients git
cd /tmp
git clone https://github.com/nic-instruction/hello-nti-310.git

#this line copies /usr/share/openldap-servers/DB_CONFIG.example from the 
#the software installed above and places the copy into /var/lib/ldap/DB_CONFIG
cp /usr/share/openldap-servers/DB_CONFIG.example /var/lib/ldap/DB_CONFIG 

#this line changes the group and user ownership and gives it to /var/lib/ldap/DB_CONFIG
#the dot is a shortcode code, it can also be written as ldap:ldap (group and user)
chown ldap. /var/lib/ldap/DB_CONFIG

#this line enables slapd wich is the daemon name for ldap
systemctl enable slapd

#this line starts slapd
systemctl start slapd

#this line is installs httpd for the apache server to operate (http)
yum -y install httpd

#this line installs the web app for administring ldap servers
yum -y install phpldapadmin

#TEACHER COMMENTS/EDITS
# some source editing
# Tell SE linux what's going on, so that it doesn't freek

#this line allows the apcache server to connect to the ldap server without the ldap server
#shutting itself down
setsebool -P httpd_can_connect_ldap on

#this line enables the daemon software installed earlier
#on the apache server so that it can answer requests for http  
systemctl enable httpd

#this lin starts the server's software
systemctl start httpd

#modifies httpd.conf so you can access it from an apache server/external html
sed -i 's,Require local,#Require local\n    Require all granted,g' /etc/httpd/conf.d/phpldapadmin.conf

#this line copies the config file and makes a backup in case something goes wrong later
cp /etc/phpldapadmin/config.php /etc/phpldapadmin/config.php.orig

#this line was needed to bring over code from the git repository
cp /tmp/hello-nti-310/config/config.php /etc/phpldapadmin/config.php

#this line is needed if the line on 45 is used becaues the state of the system things cp means something other than copy
unalias cp
#it wasn't needed in the config i was working on - i think because i didn't write line 45 but i'm not sure

#this line changed the ownership of ldap:apache and gave itto the local config??
chown ldap:apache /etc/phpldapadmin/config.php

#this line was used to move into the temp director so we could make the following
cd /tmp

#this line was needed because we needed to restart the service after changing ownership??
systemctl restart httpd.service

#this line creates a password and stores it securely
#newsecret=$(slappasswd -g)
#hardcoding on the next line for the clients to come
newsecret="mypassword"
#this line stores the password securley
newhash=$(slappasswd -s "$newsecret")
#hardcode in this line:
#newhash=(slappasswd -s "mypassword")

#this line takes the pswd and sends it to root
echo -n "$newsecret" > /root/ldap_admin_pass
#hardcode this line:
#echo -n "mypassword" > /root/ldap_admin_pass
#this line changes the read/write/execute bits
chmod 0600 /root/ldap_admin_pass

#these lines echos so that they can modify the database: 1. so that it is local, 
#2. so that it takes the old password and 3. replaces it with the new password that
#is auto generated and secure??
echo -e "dn: olcDatabase={2}hdb,cn=config
changetype: modify
replace: olcSuffix
olcSuffix: dc=nti310,dc=local
\n
dn: olcDatabase={2}hdb,cn=config
changetype: modify
replace: olcRootDN
olcRootDN: cn=ldapadm,dc=nti310,dc=local
\n
dn: olcDatabase={2}hdb,cn=config
changetype: modify
replace: olcRootPW
olcRootPW: $newhash" > db.ldif
ldapmodify -Y EXTERNAL  -H ldapi:/// -f db.ldif

# Restrict auth from external access 
echo 'dn: olcDatabase={1}monitor,cn=config
changetype: modify
replace: olcAccess
olcAccess: {0}to * by dn.base="gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth" read by dn.base="cn=ldapadm,dc=nti310,dc=local" read by * none' > monitor.ldif

#This line is used as the format to exchange data and enable the synchronization of that
#data between Lightweight Directory Access Protocol ( LDAP ) server s called Directory System Agents (DSAs)
ldapmodify -Y EXTERNAL  -H ldapi:/// -f monitor.ldif

# Generate SSL certs (the padlock on port 443 http)
openssl req -new -x509 -nodes -out /etc/openldap/certs/nti310ldapcert.pem -keyout /etc/openldap/certs/nti310ldapkey.pem -days 365 -subj "/C=US/ST=WA/L=Seattle/O=SCC/OU=IT/CN=nti310.local"

#changes the ownership from ldap to the local etc/openldap/cert file location
chown -R ldap. /etc/openldap/certs/nti*.pem

#This line places the keys inside of ldap
echo -e "dn: cn=config
changetype: modify
replace: olcTLSCertificateKeyFile
olcTLSCertificateKeyFile: /etc/openldap/certs/nti310ldapkey.pem" > certs.ldif
\n
"dn: cn=config
changetype: modify
replace: olcTLSCertificateFile
olcTLSCertificateFile: /etc/openldap/certs/nti310ldapcert.pem"

#this line does the modification of the above lines
ldapmodify -Y EXTERNAL  -H ldapi:/// -f certs.ldif

#this line tests to make sure it works
slaptest -u

#this line changes cp alias
unalias cp

#run the following schemas one at at time
ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/cosine.ldif
ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/nis.ldif 
ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/inetorgperson.ldif

#TEACHER COMMENTS Create base group and people structure
#TEACHER COMMENTS the vim base.ldif needs the spaces below, then on the command line: ldapadd -x -W -D "cn=ldapadm,dc=nti310,dc=local" -f base.ldif 
echo -e "dn: dc=nti310,dc=local
dc: nti310
objectClass: top
objectClass: domain

dn: cn=ldapadm,dc=nti310,dc=local
objectClass: organizationalRole
cn: ldapadm
description: LDAP Manager

dn: ou=People,dc=nti310,dc=local
objectClass: organizationalUnit
ou: People

dn: ou=Group,dc=nti310,dc=local
objectClass: organizationalUnit
ou: Group" > base.ldif

#This line turns off SE Linux - the security features 
setenforce 0

#this line reads the password and passes it through
ldapadd -x -W -D "cn=ldapadm,dc=nti310,dc=local" -f base.ldif -y /root/ldap_admin_pass

#LDIF Export for cn=Koda Mondragon,ou=People,dc=nti310,dc=local
# Server: NTI-310 Example LDAP Server (127.0.0.1)
# Search Scope: base
# Search Filter: (objectClass=*)
# Total Entries: 1
#
# Generated by phpLDAPadmin (http://phpldapadmin.sourceforge.net) on January 25, 2019 2:16 am
# Version: 1.2.3

echo -e "version: 1

# Entry 1: cn=Koda Mondragon,ou=People,dc=nti310,dc=local
dn: cn=Person1,ou=People,dc=nti310,dc=local
cn: Person1
gidnumber: 500
givenname: Person1
homedirectory: /home/Person1
loginshell: /bin/sh
objectclass: inetOrgPerson
objectclass: posixAccount
objectclass: top
sn: Person1
uid: Person1
uidnumber: 1001
userpassword: {SHA}R5nV3A38+e62G8u5F7tcdLoyZtg=
\n
dn: cn=Person2,ou=People,dc=nti310,dc=local
cn: Person2
gidnumber: 500
givenname: Person2
homedirectory: /home/Person2
loginshell: /bin/sh
objectclass: inetOrgPerson
objectclass: posixAccount
objectclass: top
sn: Person2
uid: Person2
uidnumber: 1002
userpassword: {SHA}R5nV3A38+e62G8u5F7tcdLoyZtg=
\n
dn: cn=Person3,ou=People,dc=nti310,dc=local
cn: Person3
gidnumber: 500
givenname: Person3
homedirectory: /home/Person3
loginshell: /bin/sh
objectclass: inetOrgPerson
objectclass: posixAccount
objectclass: top
sn: Person3
uid: Person3
uidnumber: 1003
userpassword: {SHA}R5nV3A38+e62G8u5F7tcdLoyZtg=
\n
dn: cn=Person4,ou=People,dc=nti310,dc=local
cn: Person4
gidnumber: 500
givenname: Person4
homedirectory: /home/Person4
loginshell: /bin/sh
objectclass: inetOrgPerson
objectclass: posixAccount
objectclass: top
sn: Person4
uid: Person4
uidnumber: 1004
userpassword: {SHA}R5nV3A38+e62G8u5F7tcdLoyZtg=
\n
dn: cn=Person5,ou=People,dc=nti310,dc=local
cn: Person5
gidnumber: 500
givenname: Person5
homedirectory: /home/Person5
loginshell: /bin/sh
objectclass: inetOrgPerson
objectclass: posixAccount
objectclass: top
sn: Person5
uid: Person5
uidnumber: 1005
userpassword: {SHA}R5nV3A38+e62G8u5F7tcdLoyZtg=
\n
dn: cn=KodaM,ou=People,dc=nti310,dc=local
cn: KodaM
gidnumber: 500
givenname: KodaM
homedirectory: /home/KodaM
loginshell: /bin/sh
objectclass: inetOrgPerson
objectclass: posixAccount
objectclass: top
sn: KodaM
uid: KodaM
uidnumber: 1006
userpassword: {SHA}R5nV3A38+e62G8u5F7tcdLoyZtg=" > /tmp/users.ldif

ldapadd -x -W -D "cn=ldapadm,dc=nti310,dc=local" -f /tmp/users.ldif -y /root/ldap_admin_pass

echo -e "version: 1
\n
# Entry 1: ou=Group,dc=nti310,dc=local
dn: cn=Al,ou=Group,dc=nti310,dc=local
cn: Al
gidnumber: 500
objectclass: posixGroup
objectclass: top
\n
# Entry 2: ou=Group,dc=nti310,dc=local
dn: cn=Jamie,ou=Group,dc=nti310,dc=local
cn: Jamie
gidnumber: 501
objectclass: posixGroup
objectclass: top" > /tmp/groups.ldif

ldapadd -x -W -D "cn=ldapadm,dc=nti310,dc=local" -f /tmp/groups.ldif -y /root/ldap_admin_pass
systemctl restart httpd

yum update -y && yum 
#\n

#ou: Group
#version: 1
# Entry 1: ou=Group,dc=nti310,dc=local
#dn: ou=Group3,dc=nti310,dc=local
#objectclass: organizationalUnit
#ou: Group3
#ldapadd -x -W -D "cn=ldapadm,dc=nti310,dc=local" -f /tmp/users.ldif -y /root/ldap_admin_pass

# LDIF Export for ou=Group,dc=nti310,dc=local
# Server: NTI-310 Example LDAP Server (127.0.0.1)
# Search Scope: base
# Search Filter: (objectClass=*)
# Total Entries: 1
#
# Generated by phpLDAPadmin (http://phpldapadmin.sourceforge.net) on January 25, 2019 3:53 am
# Version: 1.2.3


#for servername in $(gcloud compute instances list | awk '{print $1}' | sed "1 d" | grep -v nagios4419 );  do gcloud compute ssh --zone us-east1-b koda@$servername --command='sudo yum -y install wget && sudo wget https://raw.githubusercontent.com/dakoda17/NTI-310/master/hello-nti-310/config/nagiosclient421 && sudo bash nagiosclient421'; done

#this line restarts the system


#------------------------UNUSED PIECES FROM HERE DOWN--------------------------------------------------
#TEACHER COMMENTS/EDITS
# decent config guide: http://www.itzgeek.com/how-tos/linux/centos-how-tos/install-configure-phpldapadmin-centos-7-ubuntu-16-04.html
#Note: LDAP comes up completely insecure, with Anonymous login enabled by default... this is not a good and happy thing, so fix 
#it in the config file
#(prompt for user input), the following is currently a manual config, but could be automated fairly easily
#slappasswd
#open tcp port 389
#don't use the eco on the first line
#this went into a vim

#the next two lines declares what is going on during the install
#however, in class we made a not of not using them until we were ready to automate
#echo "phpldapadmin is now up and running"

#this line declares what is going on during the install
#echo "we are configuring ldap and ldapadmin"

#echo "dn: olcDatabase={2}hdb,cn=config
#changetype: modify
#replace: olcSuffix
#olcSuffix: dc=nti310,dc=local

#then run on command line: ldapmodify -Y EXTERNAL  -H ldapi:/// -f db.ldif
#now vim
#dn: olcDatabase={2}hdb,cn=config
#changetype: modify
#replace: olcRootDN
#olcRootDN: cn=ldapadm,dc=nti310,dc=local

#then run on command line: ldapmodify -Y EXTERNAL  -H ldapi:/// -f db.ldif
#now vim
#dn: olcDatabase={2}hdb,cn=config
#changetype: modify
#replace: olcRootPW
#olcRootPW: $newhash" >> db.ldif

#ldapmodify -Y EXTERNAL  -H ldapi:/// -f db.ldif

# Use Certs in LDAP
# split this into two. had to run the second half first, then the ldapmodify file, then the first half second, then the ldapmodify file again
# in order to make it work it had to be run from the commandline using echo in front of each other

#this is the second that has to run first - use ecoh in front of first line

#ldapmodify -Y EXTERNAL -H ldapi:/// -f db.ldif

#This line 
#didn't use any part of this line past base.ldif

#on the web page didn't get in until the file looked liked this:
##  Web-based tool for managing LDAP servers

#Alias /phpldapadmin /usr/share/phpldapadmin/htdocs
#Alias /ldapadmin /usr/share/phpldapadmin/htdocs
#<Directory /usr/share/phpldapadmin/htdocs>
#  <IfModule mod_authz_core.c>
    # Apache 2.4
    #Require local
#    Require all granted
#  </IfModule>
#  <IfModule !mod_authz_core.c>
    # Apache 2.2
#    Order Deny,Allow
#    Deny from all
#    Allow from All
#    Allow from ::1
#  </IfModule>
#</Directory>
