#!/bin/bash
#This script migrates djangopostres
yum install -y epel-release
yum -y install python-pip
pip install virtualenv
pip install --upgrade pip

yum install -y telnet

#make a dir on root called myproject, cd into it, activate, and run from inside 
mkdir ~/myproject
cd ~/myproject
virtualenv myprojectenv
#
source myprojectenv/bin/activate
pip install django psycopg2
django-admin.py startproject myproject .

yum update -y && yum install -y rsyslog
systemctl start rsyslog
systemctl enable rsyslog

cp /etc/rsyslog.conf /etc/rsyslog.bak

#needs to be the name of the client rsyslog server
echo "*.* @@10.142.0.204:514" >> /etc/rsyslog.conf
#restart rsyslog
sudo systemctl restart rsyslog

#vim into vim  ~/myproject/myproject/settings.py
#and change the following to: 
#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.postgresql_psycopg2',
#        'NAME': 'myproject',
#        'USER': 'myprojectuser',
#        'PASSWORD': 'password',
#        'HOST': 'postgresa',
#        'PORT': '5432',
#    }
#}

python manage.py makemigrations
python manage.py migrate

wget -O ~/myproject/myproject/settings.py https://github.com/dakoda17/NTI-310/blob/master/settings.py

#for servername in $(gcloud compute instances list | awk '{print $1}' | sed "1 d" | grep -v nagios4419 );  do gcloud compute ssh --zone us-east1-b koda@$servername --command='sudo yum -y install wget && sudo wget https://raw.githubusercontent.com/dakoda17/NTI-310/master/hello-nti-310/config/nagiosclient421 && sudo bash nagiosclient421'; done
