#!/bin/bash
#Use https://www.digitalocean.com/community/tutorials/how-to-use-postgresql-with-your-django-application-on-centos-7
#(Links to an external site.)Links to an external site.
#Postgres: Like a sql server but totally cl
#Allow http and https to allow webbased access/traffic
#Attach djanog front-end to teh back end of postgres

#MAY NOT NEED FIRST LINE
sudo yum install epel-release

#install packages gcc=gnu compiler
yum -y install python-pip python-devel gcc postgresql-server postgresql-devel postgresql-contrib
postgresql-setup initdb
systemctl start postgresql

vim /var/lib/pgsql/data/pg_hba.conf
#the automation for this vim file
sed -i 's,host    all             all             127.0.0.1/32            ident,host     all             all             127.0.0.1/32            md5,g' /var/lib/pgsql/data/pg_hba.conf
sed -i 's,host    all             all             ::1/128                 ident,host     all             all             127.0.0.1/32            md5,g' /var/lib/pgsql/data/pg_hba.conf

systemctl restart postgresql
systemctl enable postgresql

#for automation
sudo -u postgres ""

#manually
#su -u postgres ""

echo "CREATE DATABASE myproject;
CREATE USER myprojectuser WITH PASSWORD 'password';
ALTER ROLE myprojectuser SET client_encoding TO 'utf8';
ALTER ROLE myprojectuser SET default_transaction_isolation TO 'read committed';
ALTER ROLE myprojectuser SET timezone TO 'UTC';
GRANT ALL PRIVILEGES ON DATABASE myproject TO myprojectuser;" >> /tmp/tempfile
\q
exit

sudo -u postgres "psql -f /tmp/tempfile" 
#it could be this line instead:
#sudo -u postgres /bin/psql -f /tmp/tempfile
