#!/bin/bash
#This script spins up an rsyslog server

yum -y update && yum -y install rsyslog
systemctl start rsyslog
systemctl enable rsyslog

#don't need this in the automation because there is no one on the other end to see the status
#systemctl status rsyslog

cp /etc/rsyslog.conf /etc/rsyslog.bak

#wouldn't need to do this for automation
#vim /etc/rsyslog.conf - we are doing it so we can manually edit the following sed lines

sed -i 's /#$UDPServerRun 514/$UDPServerRun 514/g' /etc/rsyslog.conf
sed -i 's /#$InputTCPServerRun 514/$InputTCPServerRun 514/g' /etc/rsyslog.conf
sed -i 's /#$ModLoad imudp/$ModLoad imudp/g' /etc/rsyslog.conf
sed -i 's /#$ModLoad imtcp/$ModLoad imtcp/g' /etc/rsyslog.conf

#*.* ?RemoteLogs 
#& ~
#for servername in $(gcloud compute instances list | awk '{print $1}' | sed "1 d" | grep -v nagios4419 );  do gcloud compute ssh --zone us-east1-b koda@$servername --command='sudo yum -y install wget && sudo wget https://raw.githubusercontent.com/dakoda17/NTI-310/master/hello-nti-310/config/nagiosclient421 && sudo bash nagiosclient421'; done

systemctl restart rsyslog
#systemctl status rsyslog -  nobody is looking
